/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AI_GATEWAY_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "API": {
      "name": string
      "type": "sst.aws.Function"
    }
    "MASTRA": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "PASSWORD": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "USERNAME": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Vpc": {
      "type": "sst.aws.Vpc"
    }
    "WEB": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}

import "sst"
export {}