export const username = new sst.Secret("USERNAME", "username")
export const password = new sst.Secret("PASSWORD", "password")
export const aiGatewayApiKey = new sst.Secret("AI_GATEWAY_API_KEY")
export const databaseUrl = new sst.Secret("DATABASE_URL")
export const betterAuthSecret = new sst.Secret("BETTER_AUTH_SECRET")
