// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"cn/blocks/introduction.mdx": () => import("../../../packages/content/src/cn/blocks/introduction.mdx?collection=docs"), "en/blocks/introduction.mdx": () => import("../../../packages/content/src/en/blocks/introduction.mdx?collection=docs"), "en/blocks/resume.mdx": () => import("../../../packages/content/src/en/blocks/resume.mdx?collection=docs"), "en/writings/agent-memory.mdx": () => import("../../../packages/content/src/en/writings/agent-memory.mdx?collection=docs"), "en/writings/agent-observability.mdx": () => import("../../../packages/content/src/en/writings/agent-observability.mdx?collection=docs"), "en/writings/figma-design.mdx": () => import("../../../packages/content/src/en/writings/figma-design.mdx?collection=docs"), "en/writings/frontend-concepts.mdx": () => import("../../../packages/content/src/en/writings/frontend-concepts.mdx?collection=docs"), "en/writings/hive.mdx": () => import("../../../packages/content/src/en/writings/hive.mdx?collection=docs"), "en/writings/production-rag.mdx": () => import("../../../packages/content/src/en/writings/production-rag.mdx?collection=docs"), "en/writings/things-i-believe.mdx": () => import("../../../packages/content/src/en/writings/things-i-believe.mdx?collection=docs"), "en/works/kleya.mdx": () => import("../../../packages/content/src/en/works/kleya.mdx?collection=docs"), "en/works/luthen.mdx": () => import("../../../packages/content/src/en/works/luthen.mdx?collection=docs"), "en/works/obi.mdx": () => import("../../../packages/content/src/en/works/obi.mdx?collection=docs"), "en/works/rey.mdx": () => import("../../../packages/content/src/en/works/rey.mdx?collection=docs"), "en/works/skia.mdx": () => import("../../../packages/content/src/en/works/skia.mdx?collection=docs"), "en/works/yavin.mdx": () => import("../../../packages/content/src/en/works/yavin.mdx?collection=docs"), "hk/blocks/introduction.mdx": () => import("../../../packages/content/src/hk/blocks/introduction.mdx?collection=docs"), }),
};
export default browserCollections;